### ISSUE TITLE
Getting Started Package issues with 1.4

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/universal-crossplane#182]
### What happened?

When trying to install the configuration package at <https://raw.githubusercontent.com/upbound/universal-crossplane/main/docs/getting-started/install.yaml>, user gets an `10s     Warning  LintPackage       configurationrevision/getting-started-21a26936d1e2  package is not compatible with Crossplane version (v1.4.0-up.1)` error and the package never becomes healthy.

Using [ignoreCrossplaneConstraints](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Configuration/v1@v1.4.1#spec-ignoreCrossplaneConstraints) allowed the configuration package (and dependent aws provider) to be installed.

### How can we reproduce it?

- install new UXP 1.4 cluster
- `kubectl apply -f https://raw.githubusercontent.com/upbound/universal-crossplane/main/docs/getting-started/install.yaml`

### Workaround

Set `ignoreCrossplaneConstraints` in your configuration definition.

You can apply the following configuration:

```
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: getting-started
spec:
  package: registry.upbound.io/upbound/getting-started:latest
  ignoreCrossplaneConstraints: true
```
