### ISSUE TITLE
Upbound agent does not respect proxy environment variables while connecting to NATS server

### ISSUE THREAD

**Issue by ytsarev** [upbound/universal-crossplane#193]
### What happened?

Upbound agent does not respect proxy environment variables while connecting to NATS server

### How can we reproduce it?

Propagate http(s) proxy environment variables using the values.yaml config similar to
```
agent:
  config:
    envVars:
      HTTP_PROXY: http://proxy:8080
      HTTPS_PROXY: http://proxy:8080
      http_proxy: http://proxy:8080
      https_proxy: http://proxy:8080
```

Observe that upbound-agent pod is failing with
```
upbound-agent: error: failed to create new agent proxy: failed to connect NATS: nats: no servers available for connection
```

### What environment did it happen in?
```
upbound-main-1.5.0-rc.0.up.1.13.gcf7e4e9
```
which included #189
