### ISSUE TITLE
Create custom build without `aggregationRule`

### ISSUE THREAD

**Issue by Piotr1215** [upbound/universal-crossplane#299]
### What problem are you facing?

UXP requires admin privileges on the `crossplane` service account due to

```yaml
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      [rbac.crossplane.io/aggregate-to-crossplane](http://rbac.crossplane.io/aggregate-to-crossplane): "true"
```

This prevents UXP from working in restricted environments and is currently blocking progress on https://github.com/upbound/platform-core/issues/426.

### How could Upbound help solve your problem?

Create a custom build without the `aggregationRule`
