### ISSUE TITLE
CRD for `aws.upbound.io` not found even after installing `provider-family-aws provider`

### ISSUE THREAD

**Issue by preetsindhal** [upbound/universal-crossplane#396]
kind `ProviderConfig` of api `aws.upbound.io` not found even after installing `provider-family-aws` provider

provider is installed with warning:
`Warning  UnpackPackage  24s (x10 over 4m27s)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: serviceaccounts "crossplane" not found`

Error:

`ProviderConfig/universal-crossplane/aws-provider-upbound dry-run failed: failed to get API group resources: unable to retrieve the complete list of server APIs: aws.upbound.io/v1beta1: the server could not find the requested resource`

Yaml 

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config-upbound
  namespace: universal-crossplane
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxx:role/K8s-crossplane
spec:
  podSecurityContext:
    fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v0.39.0
  controllerConfigRef:
    name: aws-config-upbound
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider-upbound
  namespace: universal-crossplane
spec:
  credentials:
    source: InjectedIdentity


```
